cargo-features = ["edition2021"]
[package]
name = "ips-patch"
version = "0.0.0"
authors = ["Craig M. Brandenburg <c.m.brandenburg@gmail.com>", "Anthony Cicchetti <me@purpleonthe.cloud>"]
edition = "2021"

[dependencies]
structopt = "0.3"
eyre = "0.6"
thiserror = "1.0"